# Pipeline Configuration Example - All Filters Demonstrated
# This file shows all available filters with enable/disable flags

screening:
  # Stock screening filters - Each filter can be enabled/disabled independently
  # Only enabled filters will be applied during screening
  filters:
    # Price Range Filter: Filter stocks by opening price
    # Useful for focusing on stocks within a specific price bracket
    price_range:
      enabled: true
      min_price: 5        # Minimum opening price (avoid penny stocks)
      max_price: 1000     # Maximum opening price (avoid very high-priced stocks)
    
    # Price vs Moving Average Filter: Compare opening price to moving average
    # Helps identify stocks trading above/below their trend
    price_vs_ma:
      enabled: true
      ma_period: 20       # Moving average period (20, 50, or 200 days)
      condition: "above"  # Filter for prices "above" or "below" MA
    
    # RSI Filter: Relative Strength Index filter
    # Identifies overbought/oversold conditions
    rsi:
      enabled: true
      rsi_period: 14          # RSI calculation period (standard is 14)
      threshold: 30.0     # RSI threshold (30 for oversold, 70 for overbought)
      condition: "below"  # Filter for RSI "above" or "below" threshold
    
    # Gap Filter: Filter by gap between today's open and yesterday's close
    # Useful for gap trading strategies
    gap:
      enabled: true
      gap_threshold: 2.0  # Minimum gap percentage (e.g., 2 = 2%)
      direction: "up"     # Gap direction: "up", "down", or "both"
    
    # Previous Day Dollar Volume Filter: Filter by yesterday's dollar volume
    # Ensures sufficient liquidity based on previous day's trading
    prev_day_dollar_volume:
      enabled: true
      min_dollar_volume: 10000000  # Minimum dollar volume ($10M default)
    
    # Relative Volume Filter: Compare recent volume to historical average
    # Identifies stocks with unusual volume activity
    relative_volume:
      enabled: true
      recent_days: 2      # Number of recent days for volume average
      lookback_days: 20   # Number of historical days for comparison
      min_ratio: 1.5      # Minimum ratio of recent/historical volume
  
  # Date range for screening
  date_range:
    start: "2025-08-04"
    end: "2025-08-04" 
  
  # Use all US stocks or specific list
  use_all_us_stocks: true

backtesting:
  # Strategy to use for backtesting
  strategy: "MarketStructure"
  
  # Backtest date range (can be different from screening)
  date_range:
    start: "2025-08-04"
    end: "2025-08-04"
  
  # Starting capital for each backtest
  initial_cash: 100000
  
  # Strategy-specific parameters
  parameters:
    pivot_bars: 2
    lower_timeframe: "5min"
    # Additional MarketStructure parameters can be added here
  
  # Data resolution for backtesting
  resolution: "Daily"  # Options: Tick, Second, Minute, Hour, Daily

execution:
  # Number of backtests to run in parallel
  parallel_backtests: 5
  
  # Maximum number of backtests to execute (0 = unlimited)
  max_backtests: 0
  
  # Delay between starting different backtests (in seconds)
  startup_delay: 10
  
  # Timeout for each backtest in seconds
  timeout_per_backtest: 300
  
  # Number of retry attempts for failed backtests
  retry_attempts: 2
  
  # Whether to continue on failures
  continue_on_error: true

output:
  # Directory to save results
  directory: "./pipeline_results"
  
  # Output formats for statistics
  formats: 
    - "json"
    - "csv"
    - "html"
  
  # Whether to print statistics to console
  print_to_console: true
  
  # Cleanup settings
  cleanup_logs: true
  archive_before_cleanup: true
  archive_format: "tar.gz"

# Storage configuration
storage:
  # Enable or disable database storage
  enabled: true
  
  # Store results immediately after each backtest completes
  store_immediately: true
  
  # Cleanup files after successful storage
  cleanup_after_storage: true
  
  # Archive important files before cleanup
  archive_before_cleanup: true
  
  # Database table for backtest results
  table_name: "market_structure_results"

# Caching configuration
caching:
  # Enable or disable caching
  enabled: true
  
  # Cache time-to-live settings
  screener_ttl_hours: 24  # How long to cache screener results
  backtest_ttl_days: 7    # How long to cache backtest results
  
  # Cache cleanup
  cleanup_on_startup: true  # Clean expired entries when pipeline starts
  
  # Cache statistics
  show_stats_on_completion: true  # Display cache hit/miss stats at end

# Advanced settings
advanced:
  # Resource limits
  max_memory_percent: 80
  max_cpu_percent: 90
  
  # Logging
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "./pipeline.log"
  
  # Database settings
  save_to_database: false
  database_table: "pipeline_results"