# Test configuration for verifying new schema integration
# This config tests all filter types to ensure proper mapping

screening:
  filters:
    # Price Range Filter
    price_range:
      enabled: true
      min_price: 10
      max_price: 500
    
    # Price vs MA Filter - Testing with SMA50
    price_vs_ma:
      enabled: true
      ma_period: 50
      condition: "above"
    
    # RSI Filter - Testing oversold condition
    rsi:
      enabled: true
      rsi_period: 14
      threshold: 35.0
      condition: "below"
    
    # Gap Filter - Testing with "both" direction
    gap:
      enabled: true
      gap_threshold: 1.0
      direction: "both"  # Will be mapped to "any" in database
    
    # Previous Day Dollar Volume Filter
    prev_day_dollar_volume:
      enabled: true
      min_dollar_volume: 5000000  # $5M
    
    # Relative Volume Filter
    relative_volume:
      enabled: true
      recent_days: 3
      lookback_days: 30
      min_ratio: 2.0
  
  date_range:
    start: "2025-08-04"
    end: "2025-08-04"
  
  use_all_us_stocks: true

backtesting:
  strategy: "MarketStructure"
  date_range:
    start: "2025-08-04"
    end: "2025-08-04"
  initial_cash: 100000
  parameters:
    pivot_bars: 2
    lower_timeframe: "5min"
  resolution: "Daily"

execution:
  parallel_backtests: 1
  max_backtests: 1  # Just test one symbol
  startup_delay: 5
  timeout_per_backtest: 300
  retry_attempts: 1
  continue_on_error: true

output:
  directory: "./pipeline_results"
  formats: ["json"]
  print_to_console: true
  cleanup_logs: true
  archive_before_cleanup: false

storage:
  enabled: true
  store_immediately: true
  cleanup_after_storage: true
  archive_before_cleanup: false
  table_name: "market_structure_results"

caching:
  enabled: true
  screener_ttl_hours: 24
  backtest_ttl_days: 7
  cleanup_on_startup: false
  show_stats_on_completion: true

advanced:
  max_memory_percent: 80
  max_cpu_percent: 90
  log_level: "INFO"
  log_file: "./pipeline_test_new_schema.log"
  save_to_database: false
  database_table: "pipeline_results"