# Minimal Pipeline Configuration - Only Essential Filters
# This configuration uses only the most basic filters for quick screening

screening:
  # Stock screening filters - Only essential filters enabled
  filters:
    # Price Range Filter: Basic price filtering
    price_range:
      enabled: true
      min_price: 10       # Focus on stocks above $10
      max_price: 500      # Exclude very expensive stocks
    
    # Price vs MA: Disabled for speed
    price_vs_ma:
      enabled: false
      ma_period: 20
      condition: "above"
    
    # RSI: Disabled for speed
    rsi:
      enabled: false
      period: 14
      threshold: 30.0
      condition: "below"
    
    # Gap Filter: Disabled
    gap:
      enabled: false
      gap_threshold: 2.0
      direction: "up"
    
    # Previous Day Dollar Volume: Essential for liquidity
    prev_day_dollar_volume:
      enabled: true
      min_dollar_volume: 5000000  # $5M minimum for liquidity
    
    # Relative Volume: Disabled
    relative_volume:
      enabled: false
      recent_days: 2
      lookback_days: 20
      min_ratio: 1.5
  
  # Single day screening for speed
  date_range:
    start: "2025-08-04"
    end: "2025-08-04" 
  
  use_all_us_stocks: true

backtesting:
  strategy: "MarketStructure"
  
  # Same day backtesting
  date_range:
    start: "2025-08-04"
    end: "2025-08-04"
  
  initial_cash: 100000
  
  parameters:
    pivot_bars: 2
    lower_timeframe: "5min"
  
  resolution: "Daily"

execution:
  # Reduced parallelism for testing
  parallel_backtests: 3
  
  # Limit backtests for quick testing
  max_backtests: 2
  
  startup_delay: 5
  timeout_per_backtest: 300
  retry_attempts: 1
  continue_on_error: true

output:
  directory: "./pipeline_results"
  formats: ["json"]
  print_to_console: true
  cleanup_logs: true
  archive_before_cleanup: false

storage:
  enabled: true
  store_immediately: true
  cleanup_after_storage: true
  archive_before_cleanup: false
  table_name: "market_structure_results"

caching:
  enabled: true
  screener_ttl_hours: 24
  backtest_ttl_days: 7
  cleanup_on_startup: true
  show_stats_on_completion: true

advanced:
  max_memory_percent: 80
  max_cpu_percent: 90
  log_level: "INFO"
  log_file: "./pipeline.log"
  save_to_database: false