# Test Pipeline Configuration for Multi-Day Screener-Backtest Pipeline
# This file tests the day-by-day processing with a multi-day range

screening:
  # Stock screening filters - Each filter can be enabled/disabled independently
  filters:
    # Price Range Filter: Filter stocks by opening price
    price_range:
      enabled: true
      min_price: 5        # Minimum opening price
      max_price: 1000     # Maximum opening price
    
    # Price vs Moving Average Filter: Compare opening price to moving average
    price_vs_ma:
      enabled: true
      ma_period: 20       # Moving average period (20, 50, or 200)
      condition: "above"  # Filter for prices "above" or "below" MA
    
    # RSI Filter: Relative Strength Index filter
    rsi:
      enabled: false
      rsi_period: 14      # RSI calculation period
      threshold: 30.0     # RSI threshold (e.g., 30 for oversold, 70 for overbought)
      condition: "below"  # Filter for RSI "above" or "below" threshold
    
    # Gap Filter: Filter by gap between today's open and yesterday's close
    gap:
      enabled: true
      gap_threshold: 2.0  # Minimum gap percentage (e.g., 2 = 2%)
      direction: "up"     # Gap direction: "up", "down", or "both"
    
    # Previous Day Dollar Volume Filter: Filter by yesterday's dollar volume
    prev_day_dollar_volume:
      enabled: true
      min_dollar_volume: 10000000  # Minimum dollar volume ($10M default)
    
    # Relative Volume Filter: Compare recent volume to historical average
    relative_volume:
      enabled: true
      recent_days: 2      # Number of recent days for volume average
      lookback_days: 20   # Number of historical days for comparison
      min_ratio: 1.5      # Minimum ratio of recent/historical volume
  
  # Date range for screening - Testing with a week of trading days
  date_range:
    start: "2025-08-01"  # Thursday
    end: "2025-08-07"    # Wednesday (includes weekend which will be skipped)
  
  # Use all US stocks or specific list
  use_all_us_stocks: true

backtesting:
  # Strategy to use
  strategy: "MarketStructure"
  
  # Backtest date range (can be different from screening)
  date_range:
    start: "2025-08-01"
    end: "2025-08-07"
  
  # Starting capital
  initial_cash: 100000
  
  # Strategy-specific parameters
  parameters:
    pivot_bars: 2
    lower_timeframe: "1min"
    # MarketStructure specific settings can go here
  
  # Data resolution for backtesting
  resolution: "Daily"  # Options: Tick, Second, Minute, Hour, Daily

execution:
  # Number of backtests to run in parallel
  parallel_backtests: 5
  
  # Maximum number of backtests to execute per day for testing
  # Set to a low number for testing
  max_backtests: 3
  
  # Delay between starting different backtests (in seconds)
  # This prevents LEAN CLI module installation conflicts
  startup_delay: 10
  
  # Timeout for each backtest in seconds
  # Increase this value if backtests are timing out (default: 300 = 5 minutes)
  timeout_per_backtest: 300
  
  # Number of retry attempts for failed backtests
  retry_attempts: 2
  
  # Whether to continue on failures
  continue_on_error: true

output:
  # Directory to save results
  directory: "./pipeline_results_multiday_test"
  
  # Output formats for statistics
  formats: 
    - "json"
    - "csv"
    - "html"
  
  # Whether to print statistics to console
  print_to_console: true
  
  # Cleanup settings
  cleanup_logs: false
  archive_before_cleanup: false
  archive_format: "tar.gz"  # or "zip"

# Storage configuration
storage:
  # Enable or disable database storage
  enabled: true
  
  # Store results immediately after each backtest completes
  store_immediately: true
  
  # Cleanup files after successful storage
  cleanup_after_storage: true
  
  # Archive important files before cleanup
  archive_before_cleanup: false
  
  # Database table for backtest results
  table_name: "market_structure_results"

# Caching configuration
caching:
  # Enable or disable caching
  enabled: true
  
  # Cache time-to-live settings
  screener_ttl_hours: 24  # How long to cache screener results
  backtest_ttl_days: 7    # How long to cache backtest results
  
  # Cache cleanup
  cleanup_on_startup: false  # Clean expired entries when pipeline starts
  
  # Cache statistics
  show_stats_on_completion: true  # Display cache hit/miss stats at end

# Advanced settings
advanced:
  # Resource limits
  max_memory_percent: 80
  max_cpu_percent: 90
  
  # Logging
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "./pipeline_multiday_test.log"
  
  # Database settings (if needed)
  save_to_database: true
  database_table: "pipeline_results"