# Pipeline Configuration for Screener-Backtest Pipeline
# This file configures all aspects of the end-to-end pipeline

screening:
  # Stock screening filters
  filters:
    price_range:
      min_price: 5
      max_price: 1000
    gap:
      gap_threshold: 2.0
      direction: "up"
    prev_day_dollar_volume:
      min_dollar_volume: 10000000
    relative_volume:
      recent_days: 2
      lookback_days: 20
      min_ratio: 1.5
  
  # Date range for screening
  date_range:
    start: "2025-08-04"
    end: "2025-08-04" 
  
  # Use all US stocks or specific list
  use_all_us_stocks: true

backtesting:
  # Strategy to use
  strategy: "MarketStructure"
  
  # Backtest date range (can be different from screening)
  date_range:
    start: "2025-08-04"
    end: "2025-08-04"
  
  # Starting capital
  initial_cash: 100000
  
  # Strategy-specific parameters
  parameters:
    pivot_bars: 2
    lower_timeframe: "5min"
    # MarketStructure specific settings can go here
  
  # Data resolution for backtesting
  resolution: "Daily"  # Options: Tick, Second, Minute, Hour, Daily

execution:
  # Number of backtests to run in parallel
  parallel_backtests: 5
  
  # Delay between starting different backtests (in seconds)
  # This prevents LEAN CLI module installation conflicts
  startup_delay: 10
  
  # Timeout for each backtest in seconds
  # Increase this value if backtests are timing out (default: 300 = 5 minutes)
  timeout_per_backtest: 300
  
  # Number of retry attempts for failed backtests
  retry_attempts: 2
  
  # Whether to continue on failures
  continue_on_error: true

output:
  # Directory to save results
  directory: "./pipeline_results"
  
  # Output formats for statistics
  formats: 
    - "json"
    - "csv"
    - "html"
  
  # Whether to print statistics to console
  print_to_console: true
  
  # Cleanup settings
  cleanup_logs: true
  archive_before_cleanup: true
  archive_format: "tar.gz"  # or "zip"

# Advanced settings
advanced:
  # Resource limits
  max_memory_percent: 80
  max_cpu_percent: 90
  
  # Logging
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "./pipeline.log"
  
  # Database settings (if needed)
  save_to_database: false
  database_table: "pipeline_results"