# Test configuration for verifying the join fix
screening:
  date_range:
    start: "2025-08-01"
    end: "2025-08-01"  # Single day test
  filters:
    price_range:
      enabled: true
      min_price: 1
      max_price: 20
    price_vs_ma:
      enabled: false
    rsi:
      enabled: false
    gap:
      enabled: false
    prev_day_dollar_volume:
      enabled: true
      min_dollar_volume: 10000000  # 10M
    relative_volume:
      enabled: false

backtesting:
  strategy: "MarketStructure"
  initial_cash: 100000
  resolution: "Minute"
  date_range:  # Optional, will be overridden by day-by-day processing
    start: "2025-08-01"
    end: "2025-08-01"
  parameters:
    pivot_bars: 1
    lower_timeframe: "1min"

execution:
  parallel_backtests: 2
  timeout_per_backtest: 300
  retry_attempts: 1
  continue_on_error: true
  max_backtests: 2  # Limit to 2 symbols for testing
  startup_delay: 5.0

output:
  directory: "pipeline_results"
  formats: ["json", "csv", "html"]
  print_to_console: true
  cleanup_logs: false
  archive_before_cleanup: false

caching:
  enabled: true
  screener_ttl_hours: 24
  backtest_ttl_days: 7
  cleanup_on_startup: false
  show_stats_on_completion: true

storage:
  enabled: true
  cleanup_after_storage: true